# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fadd7d128e3c91460e5394ee8a597af3ffb9a42b50efb8aa8b463754efde61edd83094fce0eb0cb56d2e89305bd4f5ce2e828da2264bd9353b655901786738e0

test:
  secret_key_base: 7ddf56cdf10b3b5963da4a87fa784dd817c8e8bdd8132a8a15befb3dbdcb2e4a682598a4a60e1ff62bef6b966da5c5420c11d55bc1c50b50145bb8d8967d5223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
